{"name": "test_mul[20-4-5]", "status": "failed", "statusDetails": {"message": "AssertionError: Test Failed!!!\nassert 5 == 80", "trace": "self = <Work.test_params.TestParams object at 0x10df61470>, a = 20, b = 4\nexpected = 5\n\n    @allure.description(\"乘法计算\")\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"params.yaml\"))[\"Mul\"])\n    def test_mul(self, a, b, expected):\n        sum = mul(a, b)\n>       assert expected == sum, \"Test Failed!!!\"\nE       AssertionError: Test Failed!!!\nE       assert 5 == 80\n\ntest_params.py:63: AssertionError"}, "description": "乘法计算", "attachments": [{"name": "log", "source": "b266d4a4-f30c-4e2f-a22b-93bc4b183016-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9da5c4cc-0c3a-46c9-848f-ea6b015b0774-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "20"}, {"name": "b", "value": "4"}, {"name": "expected", "value": "5"}], "start": 1573546636612, "stop": 1573546636612, "uuid": "bed447cd-e161-4b1a-a0e2-718ac2b0c573", "historyId": "b3d94cefd657989f078a39e90cbdf4ee", "testCaseId": "6107f4c26291394d677dde20760f05d3", "fullName": "test_params.TestParams#test_mul", "labels": [{"name": "suite", "value": "test_params"}, {"name": "subSuite", "value": "TestParams"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_params"}]}