{"name": "test_add[40-40-1]", "status": "failed", "statusDetails": {"message": "AssertionError: Test Failed!!!\nassert 1 == 80", "trace": "self = <Work.test_params.TestParams object at 0x10df2fda0>, a = 40, b = 40\nexpected = 1\n\n    @allure.description(\"加法计算\")\n    @pytest.mark.parametrize(\"a,b,expected\", [(5, 7, 9),\n                                              (4, 4, 8),\n                                              (9, 9, 18),\n                                              (40, 40, 1),\n                                              (6, 5, 30)])\n    def test_add(self, a, b, expected):\n        sum = add(a, b)\n>       assert expected == sum, \"Test Failed!!!\"\nE       AssertionError: Test Failed!!!\nE       assert 1 == 80\n\ntest_params.py:51: AssertionError"}, "description": "加法计算", "attachments": [{"name": "log", "source": "b48a6faa-dbea-4781-b744-ee2fda3edaff-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9cd9c75c-ae82-40e1-ac7d-e4650a6b8691-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "40"}, {"name": "b", "value": "40"}, {"name": "expected", "value": "1"}], "start": 1573546636519, "stop": 1573546636520, "uuid": "802184d4-88a9-4fd3-85a1-f83ace540269", "historyId": "b76acea2ea277bb96d1868f183ffdb43", "testCaseId": "5e9e0a754422f4a1cda34a85c2742411", "fullName": "test_params.TestParams#test_add", "labels": [{"name": "suite", "value": "test_params"}, {"name": "subSuite", "value": "TestParams"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_params"}]}