{"name": "test_add[6-5-30]", "status": "failed", "statusDetails": {"message": "AssertionError: Test Failed!!!\nassert 30 == 11", "trace": "self = <Work.test_params.TestParams object at 0x10df37cf8>, a = 6, b = 5\nexpected = 30\n\n    @allure.description(\"加法计算\")\n    @pytest.mark.parametrize(\"a,b,expected\", [(5, 7, 9),\n                                              (4, 4, 8),\n                                              (9, 9, 18),\n                                              (40, 40, 1),\n                                              (6, 5, 30)])\n    def test_add(self, a, b, expected):\n        sum = add(a, b)\n>       assert expected == sum, \"Test Failed!!!\"\nE       AssertionError: Test Failed!!!\nE       assert 30 == 11\n\ntest_params.py:51: AssertionError"}, "description": "加法计算", "attachments": [{"name": "log", "source": "4fe901f5-4af0-47a3-a6cc-4ea3c5b0f126-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "96d83715-cfd2-4a15-9f6e-6ce049fae2d3-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "6"}, {"name": "b", "value": "5"}, {"name": "expected", "value": "30"}], "start": 1573546636527, "stop": 1573546636527, "uuid": "6a0bb71c-fdd6-47c5-8797-20de6fbfb21d", "historyId": "bf73f3d4a533c2b2864c4b0ecda83325", "testCaseId": "5e9e0a754422f4a1cda34a85c2742411", "fullName": "test_params.TestParams#test_add", "labels": [{"name": "suite", "value": "test_params"}, {"name": "subSuite", "value": "TestParams"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_params"}]}