{"name": "test_mul[8-6-2]", "status": "failed", "statusDetails": {"message": "AssertionError: Test Failed!!!\nassert 2 == 48", "trace": "self = <Work.test_params.TestParams object at 0x10df5d7f0>, a = 8, b = 6\nexpected = 2\n\n    @allure.description(\"乘法计算\")\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"params.yaml\"))[\"Mul\"])\n    def test_mul(self, a, b, expected):\n        sum = mul(a, b)\n>       assert expected == sum, \"Test Failed!!!\"\nE       AssertionError: Test Failed!!!\nE       assert 2 == 48\n\ntest_params.py:63: AssertionError"}, "description": "乘法计算", "attachments": [{"name": "log", "source": "7b6bd139-2f6d-4c66-a342-9006737c60cd-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "05865108-3f14-4b0a-acdd-63ddd3debff5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "8"}, {"name": "b", "value": "6"}, {"name": "expected", "value": "2"}], "start": 1573546636585, "stop": 1573546636585, "uuid": "03c3f9af-63bb-4ece-95ac-f729412e0406", "historyId": "4cf267f13c7b6a5585e63dff0a3af5f4", "testCaseId": "6107f4c26291394d677dde20760f05d3", "fullName": "test_params.TestParams#test_mul", "labels": [{"name": "suite", "value": "test_params"}, {"name": "subSuite", "value": "TestParams"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_params"}]}