{"name": "test_nine[3-3-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 9\n +  where 6 = add(3, 3)", "trace": "self = <Work.test_work.TestC object at 0x10b46e390>, a = 3, b = 3, expected = 9\n\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, a, b, expected):\n        logging.info(\"This is test_six!!!\")\n>       assert add(a, b) == expected\nE       assert 6 == 9\nE        +  where 6 = add(3, 3)\n\ntest_work.py:72: AssertionError"}, "attachments": [{"name": "log", "source": "b2a904a0-1dae-44f9-be24-620cbe70b3cd-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4695ae9c-6dc2-4074-8c79-f3c8ef574342-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "3"}, {"name": "expected", "value": "9"}], "start": 1570674115267, "stop": 1570674115268, "uuid": "cff92b4b-fb17-40d8-b9c5-63b2383db18b", "historyId": "1e47cfe1eb37baeaa0c789e5434618f6", "testCaseId": "94eee2a481c08a178297ee94c3c1d95a", "fullName": "test_work.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "27998-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}