{"name": "test_nine[8-6-2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 14 == 2\n +  where 14 = add(8, 6)", "trace": "self = <Work.test_work.TestC object at 0x111179a58>, a = 8, b = 6, expected = 2\n\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, a, b, expected):\n        logging.info(\"This is test_six!!!\")\n>       assert add(a, b) == expected\nE       assert 14 == 2\nE        +  where 14 = add(8, 6)\n\ntest_work.py:72: AssertionError"}, "attachments": [{"name": "log", "source": "053bb000-9e99-4c5c-a565-860f2d4a1bdd-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "34024258-f8ed-4672-990a-a30c0799de30-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "8"}, {"name": "b", "value": "6"}, {"name": "expected", "value": "2"}], "start": 1570675352237, "stop": 1570675352238, "uuid": "f8d9f41a-4581-4a0b-8a3b-c832adbbab35", "historyId": "1421ced879ca407d6d0fe92ae584a01a", "testCaseId": "94eee2a481c08a178297ee94c3c1d95a", "fullName": "test_work.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "28698-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}