{"name": "test_six[10-2-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 12 == 5\n +  where 12 = add(10, 2)", "trace": "self = <Work.test_work.TestB object at 0x104e6cf60>, a = 10, b = 2, expected = 5\n\n    @pytest.mark.parametrize(\"a,b,expected\", json.load(open(\"calc.json\")))\n    def test_six(self, a, b, expected):\n        logging.info(\"This is test_six!!!\")\n>       assert add(a, b) == expected\nE       assert 12 == 5\nE        +  where 12 = add(10, 2)\n\ntest_work.py:58: AssertionError"}, "attachments": [{"name": "log", "source": "9f5c40a4-92b9-412d-8de2-c2611bad1aff-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "eefc31e0-64c8-44b3-881e-1bff18f21f68-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "10"}, {"name": "b", "value": "2"}, {"name": "expected", "value": "5"}], "start": 1572059932682, "stop": 1572059932682, "uuid": "9b5fbbfa-991f-4c5f-b7ba-c744c5027f2b", "historyId": "e093b09795bebea712eddc35eadbcb50", "testCaseId": "33cda52eda96a5e8528fcc03f1cd347a", "fullName": "test_work.TestB#test_six", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "7295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}