{"name": "test_six[30-5-6]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 35 == 6\n +  where 35 = add(30, 5)", "trace": "self = <Work.test_work.TestB object at 0x104e4ddd8>, a = 30, b = 5, expected = 6\n\n    @pytest.mark.parametrize(\"a,b,expected\", json.load(open(\"calc.json\")))\n    def test_six(self, a, b, expected):\n        logging.info(\"This is test_six!!!\")\n>       assert add(a, b) == expected\nE       assert 35 == 6\nE        +  where 35 = add(30, 5)\n\ntest_work.py:58: AssertionError"}, "attachments": [{"name": "log", "source": "432c5879-d9e1-4d33-bd89-19690808d2f8-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a94a6bfe-4dd0-4555-ad36-7db6c8b359e6-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "30"}, {"name": "b", "value": "5"}, {"name": "expected", "value": "6"}], "start": 1572059932701, "stop": 1572059932702, "uuid": "c965efec-b918-4eda-8df4-137242cb8894", "historyId": "9252472437623d87a04201feaaae742f", "testCaseId": "33cda52eda96a5e8528fcc03f1cd347a", "fullName": "test_work.TestB#test_six", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "7295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}