{"name": "test_five", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 8\n +  where 10 = add(5, 5)", "trace": "self = <Work.test_work.TestB object at 0x104e61828>\n\n    def test_five(self):\n        logging.info(\"This is test_five!!!\")\n>       assert add(5, 5) == 8\nE       assert 10 == 8\nE        +  where 10 = add(5, 5)\n\ntest_work.py:53: AssertionError"}, "attachments": [{"name": "log", "source": "a2c67fe5-4853-4d0a-adbe-02051a644046-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "323ccf8e-ffe8-454a-9b6f-30b43b41e2fd-attachment.txt", "type": "text/plain"}], "start": 1572059932638, "stop": 1572059932639, "uuid": "beae50ca-ee1c-4bb8-bd14-5fc9bc765968", "historyId": "29300f720fe0109f83442a8fb4bb3911", "testCaseId": "f779b13c2b9c2dc87d78ea24bb4c7d7a", "fullName": "test_work.TestB#test_five", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "7295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}