{"name": "test_six[30-5-6]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 35 == 6\n +  where 35 = add(30, 5)", "trace": "self = <Work.test_work2.TestB object at 0x105f7dcf8>, module = None\nclassB_start = None, a = 30, b = 5, expected = 6\n\n    @pytest.mark.parametrize(\"a,b,expected\", json.load(open(\"calc.json\")))\n    def test_six(self, module, classB_start, a, b, expected):\n        # a = json.load(open(\"calc.json\"))\n        # print(a[\"login\"])\n        logging.info(\"This is test_six!!!\")\n>       assert add(a, b) == expected\nE       assert 35 == 6\nE        +  where 35 = add(30, 5)\n\ntest_work2.py:45: AssertionError"}, "attachments": [{"name": "log", "source": "52129f37-a0b0-429f-9995-a2be59138d1f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "35dc64ee-82f2-4cb4-8d12-950dce02c47a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "30"}, {"name": "b", "value": "5"}, {"name": "expected", "value": "6"}], "start": 1572059932588, "stop": 1572059932589, "uuid": "73abe1ac-dfb5-4ff7-b456-83be7084c260", "historyId": "f705f0da69ea3fd522db0cdf7598df1d", "testCaseId": "4f6de44d5dec1d8b69075d2b48ad4434", "fullName": "test_work2.TestB#test_six", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "7295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}