{"name": "test_three[5-7-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 12 == 9\n +  where 12 = add(5, 7)", "trace": "self = <Work.test_work.TestA object at 0x10b2dd588>, a = 5, b = 7, expected = 9\n\n    @pytest.mark.parametrize(\"a,b,expected\", [(5, 7, 9)])\n    def test_three(self, a, b, expected):\n        logging.info(\"This is test_three!!!\")\n>       assert add(a, b) == expected\nE       assert 12 == 9\nE        +  where 12 = add(5, 7)\n\ntest_work.py:40: AssertionError"}, "attachments": [{"name": "log", "source": "e98b9356-34a0-4f75-bd9f-0121dc2d8581-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "7770f325-b14b-4561-a8d9-320ba0500464-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "5"}, {"name": "b", "value": "7"}, {"name": "expected", "value": "9"}], "start": 1571538978904, "stop": 1571538978905, "uuid": "30a098f2-41e1-4edb-8b3d-b00461834e70", "historyId": "a6b207f2237805b0c194c46fc5dca99c", "testCaseId": "b4ca08758d21ef2bc07ba7322d4fdacc", "fullName": "test_work.TestA#test_three", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestA"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "2205-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}